### ISSUE TITLE
请问这条错误该怎么修改

### ISSUE THREAD

**Issue by sunlulu123** [EscapeTheWind/Edge-Computing-and-Caching-Optimization-based-on-PPO-for-Task-Offloading-in-RSU-assisted-IoV#1]
Traceback (most recent call last):
  File "C:\TASK Caching Offloading\run_this\run_different_algo1.py", line 9, in <module>
    reward, ma_hit_rate, time, ma_all_hit_rate, args = run_ppo();
  File "C:\TASK Caching Offloading\run_this\run_methods_and_outputs\run_PPO.py", line 237, in run_ppo
    rewards, ma_hit_rate, time_, ma_all_hit_rate = train(args)
  File "C:\TASK Caching Offloading\run_this\run_methods_and_outputs\run_PPO.py", line 129, in train
    s_, r, done, cur_hitrate, non_caching_hitrate, all_hitrate, time = env.step(a)
  File "C:\TASK Caching Offloading\envs\environment.py", line 490, in step
    return np.array(self.state, dtype=np.float32), reward, done, self.get_current_hitrate_reward(
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (191,) + inhomogeneous part.

**Comment by EscapeTheWind** [comment]
在我们实验室的几台机器上运行时没有出现这个问题，您有没有修改过相关代码？

**Comment by EscapeTheWind** [comment]
或者检查一下Numpy等包是否正常导入。

**Comment by sunlulu123** [comment]
感谢回复！问题已经解决
